spring.application.name=prueba-tecnica
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# 2FA
app.2fa.issuer=QPH
app.2fa.expiration-seconds=300
app.2fa.max-attempts=3

# Cambiar en un ambiente real
app.2fa.otp-pepper=x7Kp9!qL2vR8mT4zN6cW1sY3aF5hJ0uB

# EMAIL

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=molalla96mh@gmail.com
spring.mail.password=tfii agfd zivj hnin

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=molalla96mh@gmail.com
